name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build with ts
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
